services:
  - type: web
    name: n8n-service
    runtime: docker
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: GENERIC_TIMEZONE
        value: Europe/Paris
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "false"
      # Cette variable lie automatiquement n8n à la base de données créée plus bas
      - key: DB_POSTGRESDB_CONNECTION_STRING
        fromDatabase:
          name: n8n-db
          property: connectionString
      # C'est ici que tu mettras ton URL finale après le premier déploiement
      - key: WEBHOOK_URL
        value: https://remplace-moi-avec-ton-url-render.onrender.com/

databases:
  - name: n8n-db
    plan: free
    postgresMajorVersion: "16"