services:
  - type: web
    name: n8n-service
    runtime: docker
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: GENERIC_TIMEZONE
        value: Europe/Paris
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "false"
      # 👇 AJOUTE CETTE LIGNE (Limite Node.js à ~340Mo de RAM pour laisser de la marge au système)
      - key: NODE_OPTIONS
        value: --max-old-space-size=340
      - key: DB_POSTGRESDB_CONNECTION_STRING
        fromDatabase:
          name: n8n-db
          property: connectionString
      - key: WEBHOOK_URL
        value: https://remplace-moi-avec-ton-url-render.onrender.com/
        sync: false

databases:
  - name: n8n-db
    plan: free
    postgresMajorVersion: "16"